// src/components/message-reasoning.tsx
"use client";

import { ChevronDownIcon, LoaderIcon } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import { Markdown } from "./markdown";

interface MessageReasoningProps {
  isLoading: boolean;
  reasoning: string;
}

export function MessageReasoning({
  isLoading,
  reasoning,
}: MessageReasoningProps) {
  const [isExpanded, setIsExpanded] = useState(true);

  const variants = {
    collapsed: {
      height: 0,
      opacity: 0,
      marginTop: 0,
      marginBottom: 0,
    },
    expanded: {
      height: "auto",
      opacity: 1,
      marginTop: "1rem",
      marginBottom: "0.5rem",
    },
  };

  return (
    <div className="flex flex-col">
      {isLoading ? (
        <div className="flex flex-row items-center gap-2">
          <div className="font-medium">Reasoning</div>
          <div className="animate-spin">
            <LoaderIcon />
          </div>
        </div>
      ) : (
        <div className="flex flex-row items-center gap-2">
          <div className="font-medium">Reasoned for a few seconds</div>
          <button
            data-testid="message-reasoning-toggle"
            type="button"
            className="cursor-pointer"
            onClick={() => {
              setIsExpanded(!isExpanded);
            }}
          >
            <ChevronDownIcon />
          </button>
        </div>
      )}

      <AnimatePresence initial={false}>
        {isExpanded && (
          <motion.div
            data-testid="message-reasoning"
            key="content"
            initial="collapsed"
            animate="expanded"
            exit="collapsed"
            variants={variants}
            transition={{ duration: 0.2, ease: "easeInOut" }}
            style={{ overflow: "hidden" }}
            className="flex flex-col gap-4 border-l pl-4 text-zinc-600 dark:text-zinc-400"
          >
            <Markdown>{reasoning}</Markdown>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// src/lib/modules/chef/components/message-reasoning.svelte
<script lang="ts">
	import { getLock } from '$lib/hooks/lock';
	import { sanitizeMarkdown } from '$lib/utils/markdown';
	import { ChevronDown, LoaderCircle } from '@lucide/svelte';
	import { tick } from 'svelte';
	import { cubicInOut } from 'svelte/easing';
	import { slide } from 'svelte/transition';
	let { loading, reasoning }: { loading: boolean; reasoning: string } = $props();
	let expanded = $state(false);
	const scrollLock = getLock('messages-scroll');

	function lockScrolling() {
		scrollLock.locked = true;
	}

	function unlockScrolling() {
		tick().then(() => {
			scrollLock.locked = false;
		});
	}
</script>

<div class="flex flex-col">
	{#if loading}
		<div class="flex flex-row items-center gap-2">
			<div class="font-medium">Reasoning</div>
			<div class="animate-spin">
				<LoaderCircle />
			</div>
		</div>
	{:else}
		<div class="flex flex-row items-center gap-2">
			<div class="font-medium">Reasoned for a few seconds</div>
			<!-- svelte-ignore a11y_click_events_have_key_events -->
			<!-- svelte-ignore a11y_no_static_element_interactions -->
			<div
				class="cursor-pointer"
				onclick={() => {
					expanded = !expanded;
				}}
			>
				<ChevronDown />
			</div>
		</div>
	{/if}

	{#if expanded}
		<div
			transition:slide={{ duration: 200, easing: cubicInOut }}
			onintrostart={lockScrolling}
			onintroend={unlockScrolling}
			onoutrostart={lockScrolling}
			onoutroend={unlockScrolling}
			class="mt-4 mb-2 flex flex-col gap-4 border-l pl-4 text-zinc-600 dark:text-zinc-400"
		>
			<p class="text-sm leading-relaxed">
				<!-- eslint-disable-next-line svelte/no-at-html-tags -->
				{@html sanitizeMarkdown(reasoning)}
			</p>
		</div>
	{/if}
</div>
