// src/app/(authenticated)/recipes/[id]/page.tsx
import { ArrowLeft, Clock, CookingPot, Printer, Share2 } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

import { Text } from "@/components/typography";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { createClient } from "@/lib/supabase/server";
import { RecipeIngredients } from "./components/recipe-ingredients";
import { RecipeInstructions } from "./components/recipe-instructions";
import { RecipeNutrition } from "./components/recipe-nutrition";

async function getRecipe(id: string) {
  const supabase = await createClient();

  const { data: recipe, error } = await supabase
    .from("recipes")
    .select("*")
    .eq("id", Number(id))
    .single();

  if (error || !recipe) {
    return null;
  }

  return {
    id: recipe.id.toString(),
    title: recipe.title,
    description: recipe.description,
    image: recipe.image_url,
    prepTime: `${recipe.prep_time} min`,
    cookTime: `${recipe.cook_time} min`,
    servings: recipe.servings || 4,
    mealType: recipe.meal_type,
    calories: recipe.calories || 0,
    protein: recipe.protein || 0,
    carbs: recipe.carbs || 0,
    fat: recipe.fat || 0,
    ingredients: recipe.ingredients as string[],
    instructions: recipe.instructions as string[],
  };
}

export default async function RecipePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const recipe = await getRecipe(id);

  if (!recipe) {
    notFound();
  }

  return (
    <div className="container mx-auto max-w-5xl p-6">
      <div className="mb-6 flex items-center justify-between">
        <Button variant="ghost" size="sm" asChild>
          <Link href="/recipes">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Recipes
          </Link>
        </Button>
        <div className="flex gap-2">
          <Button variant="outline" size="sm">
            <Printer className="mr-2 h-4 w-4" />
            Print
          </Button>
          <Button variant="outline" size="sm">
            <Share2 className="mr-2 h-4 w-4" />
            Share
          </Button>
        </div>
      </div>

      <div className="relative mb-6 aspect-video w-full overflow-hidden rounded-lg">
        {recipe.image ? (
          <Image
            src={recipe.image}
            alt={recipe.title}
            className="object-cover"
            fill
          />
        ) : (
          <div className="flex h-full flex-col items-center justify-center gap-2">
            <CookingPot className="h-12 w-12" />
            <Text>No image provided</Text>
          </div>
        )}
        <Badge className="absolute top-4 right-4 capitalize">
          {recipe.mealType}
        </Badge>
      </div>

      <div className="mb-8">
        <h1 className="mb-2 font-bold text-3xl">{recipe.title}</h1>
        <p className="text-lg text-muted-foreground">{recipe.description}</p>
      </div>

      <div className="mb-8 grid grid-cols-2 gap-4 sm:grid-cols-4">
        <Card className="p-4 text-center">
          <div className="mb-1 flex items-center justify-center">
            <Clock className="mr-1 h-4 w-4" />
            <span className="font-medium text-sm">Prep Time</span>
          </div>
          <p className="font-semibold text-lg">{recipe.prepTime}</p>
        </Card>
        <Card className="p-4 text-center">
          <div className="mb-1 flex items-center justify-center">
            <Clock className="mr-1 h-4 w-4" />
            <span className="font-medium text-sm">Cook Time</span>
          </div>
          <p className="font-semibold text-lg">{recipe.cookTime}</p>
        </Card>
        <Card className="p-4 text-center">
          <div className="mb-1 flex items-center justify-center">
            <span className="font-medium text-sm">Total Time</span>
          </div>
          <p className="font-semibold text-lg">
            {recipe.cookTime === "0 min"
              ? recipe.prepTime
              : `${Number.parseInt(recipe.prepTime) + Number.parseInt(recipe.cookTime)} min`}
          </p>
        </Card>
        <Card className="p-4 text-center">
          <div className="mb-1 flex items-center justify-center">
            <span className="font-medium text-sm">Servings</span>
          </div>
          <p className="font-semibold text-lg">recipe.servings</p>
        </Card>
      </div>

      <RecipeNutrition
        calories={recipe.calories}
        protein={recipe.protein}
        carbs={recipe.carbs}
        fat={recipe.fat}
      />

      <Separator className="my-8" />

      <div className="grid gap-8 md:grid-cols-2">
        <RecipeIngredients
          ingredients={recipe.ingredients}
          servings={recipe.servings}
        />
        <RecipeInstructions instructions={recipe.instructions} />
      </div>
    </div>
  );
}

// src/routes/(authenticated)/recipes/[id]/+page.svelte
<script lang="ts">
  import {
    ArrowLeft,
    Clock,
    CookingPot,
    Minus,
    Plus,
    Printer,
  } from "@lucide/svelte";
  import { Badge } from "$lib/components/ui/badge";
  import { Button } from "$lib/components/ui/button";
  import { Separator } from "$lib/components/ui/separator";
  import { routes } from "$lib/constants/routes";
  import {
    RecipeIngredients,
    RecipeInstructions,
    RecipeNutrition,
    RecipeStatCard,
  } from "$lib/modules/recipes";
  import type { PageData } from "./$types";

  const { data }: { data: PageData } = $props();

  const recipe = $derived(data.recipe);
  let currentPortions = $state(data.recipe.servings);
  const multiplier = $derived(currentPortions / recipe.servings);

  // Scaled cooking times (simple linear scaling for MVP)
  const scaledPrepTime = $derived(Math.round(recipe.prepTime * multiplier));
  const scaledCookTime = $derived(Math.round(recipe.cookTime * multiplier));
  const scaledTotalTime = $derived(
    recipe.cookTime === 0 ? scaledPrepTime : scaledPrepTime + scaledCookTime
  );

  function increasePortions() {
    currentPortions += 1;
  }

  function decreasePortions() {
    if (currentPortions > 1) {
      currentPortions -= 1;
    }
  }
</script>

<div class="container mx-auto max-w-5xl p-6">
	<div class="mb-6 flex items-center justify-between">
		<Button variant="ghost" size="sm" href={routes.recipes.base}>
			<ArrowLeft class="mr-2 h-4 w-4" />
			Back to Recipes
		</Button>
		<div class="flex gap-2">
			<Button href="/recipes/{data.recipe.id}/edit">Edit Recipe</Button>
			<Button variant="outline" size="sm" onclick={() => window.print()}>
				<Printer class="mr-2 h-4 w-4" />
				Print
			</Button>
		</div>
	</div>

	<div class="relative mb-6 aspect-video w-full overflow-hidden rounded-lg">
		{#if recipe.imageUrl}
			<img src={`/${recipe.imageUrl}`} alt={recipe.title} class="h-full w-full object-cover" />
		{:else}
			<div class="flex h-full flex-col items-center justify-center gap-2">
				<CookingPot class="h-12 w-12" />
				<span>No image provided</span>
			</div>
		{/if}
		<Badge class="absolute top-4 right-4 capitalize">
			{recipe.mealType}
		</Badge>
	</div>

	<div class="mb-8">
		<h1 class="mb-2 text-3xl font-bold">{recipe.title}</h1>
		<p class="text-muted-foreground text-lg">{recipe.description || ''}</p>
		
		<!-- Portion Controls -->
		<div class="mt-4 flex items-center gap-3">
			<span class="text-sm font-medium">Portions:</span>
			<div class="flex items-center gap-2">
				<Button
					variant="outline"
					size="icon"
					class="h-8 w-8"
					onclick={decreasePortions}
					disabled={currentPortions <= 1}
				>
					<Minus class="h-4 w-4" />
					<span class="sr-only">Decrease portions</span>
				</Button>
				<span class="min-w-8 text-center font-medium">{currentPortions}</span>
				<Button variant="outline" size="icon" class="h-8 w-8" onclick={increasePortions}>
					<Plus class="h-4 w-4" />
					<span class="sr-only">Increase portions</span>
				</Button>
			</div>
			{#if currentPortions !== recipe.servings}
				<span class="text-muted-foreground text-sm">(Original: {recipe.servings})</span>
			{/if}
		</div>
	</div>

	<div class="mb-8 grid grid-cols-2 gap-4 sm:grid-cols-4">
		<RecipeStatCard icon={Clock} label="Prep Time" value={scaledPrepTime} unit=" min" />
		<RecipeStatCard icon={Clock} label="Cook Time" value={scaledCookTime} unit=" min" />
		<RecipeStatCard icon={Clock} label="Total Time" value={scaledTotalTime} unit=" min" />
		<RecipeStatCard label="Servings" value={currentPortions} />
	</div>

	<RecipeNutrition
		calories={recipe.calories}
		protein={recipe.protein}
		carbs={recipe.carbs}
		fat={recipe.fat}
		{multiplier}
	/>

	<Separator class="my-8" />

	<div class="grid h-fit gap-8 md:grid-cols-2">
		<div class="h-full">
			<RecipeIngredients ingredients={recipe.ingredients} {multiplier} />
		</div>
		<div class="h-full">
			<RecipeInstructions instructions={recipe.instructions} />
		</div>
	</div>
</div>
