// src/lib/modules/recipes/components/recipe-instructions.svelte
<script lang="ts">
	import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card';

	export let instructions: string[];
</script>

<Card>
	<CardHeader class="pb-2">
		<CardTitle class="text-lg">Instructions</CardTitle>
	</CardHeader>
	<CardContent>
		<ol class="space-y-4">
			{#each instructions as instruction, index}
				<li class="flex gap-3">
					<div
						class="bg-primary text-primary-foreground flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-sm font-medium"
					>
						{index + 1}
					</div>
					<p class="pt-0.5">{instruction}</p>
				</li>
			{/each}
		</ol>
	</CardContent>
</Card>

// src/app/(authenticated)/recipes/[id]/components/recipe-instructions.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

interface RecipeInstructionsProps {
  instructions: string[];
}

export function RecipeInstructions({ instructions }: RecipeInstructionsProps) {
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-lg">Instructions</CardTitle>
      </CardHeader>
      <CardContent>
        <ol className="space-y-4">
          {instructions.map((instruction, index) => (
            // biome-ignore lint/suspicious/noArrayIndexKey: <explanation>
            <li key={index} className="flex gap-3">
              <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary font-medium text-primary-foreground text-sm">
                {index + 1}
              </div>
              <p className="pt-0.5">{instruction}</p>
            </li>
          ))}
        </ol>
      </CardContent>
    </Card>
  );
}
