// src/lib/modules/recipes/components/recipe-nutrition.svelte
<script lang="ts">
	import {
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle
	} from '$lib/components/ui/card';
	import NutritionItem from './nutrition-item.svelte';

	interface NutritionProps {
		calories: number;
		protein: number;
		carbs: number;
		fat: number;
	}

	let { calories, protein, carbs, fat }: NutritionProps = $props();
</script>

<Card>
	<CardHeader class="pb-2">
		<CardTitle class="text-lg">Nutrition Information</CardTitle>
		<CardDescription>Per serving</CardDescription>
	</CardHeader>
	<CardContent>
		<div class="grid grid-cols-4 gap-4 text-center">
			<NutritionItem value={calories} label="Calories" />
			<NutritionItem value={protein} label="Protein" unit="g" />
			<NutritionItem value={carbs} label="Carbs" unit="g" />
			<NutritionItem value={fat} label="Fat" unit="g" />
		</div>
	</CardContent>
</Card>

// src/app/(authenticated)/recipes/[id]/components/recipe-nutrition.tsx
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

interface RecipeNutritionProps {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

export function RecipeNutrition({
  calories,
  protein,
  carbs,
  fat,
}: RecipeNutritionProps) {
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-lg">Nutrition Information</CardTitle>
        <CardDescription>Per serving</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-4 gap-4 text-center">
          <div>
            <p className="font-bold text-2xl">{calories}</p>
            <p className="text-muted-foreground text-sm">Calories</p>
          </div>
          <div>
            <p className="font-bold text-2xl">{protein}g</p>
            <p className="text-muted-foreground text-sm">Protein</p>
          </div>
          <div>
            <p className="font-bold text-2xl">{carbs}g</p>
            <p className="text-muted-foreground text-sm">Carbs</p>
          </div>
          <div>
            <p className="font-bold text-2xl">{fat}g</p>
            <p className="text-muted-foreground text-sm">Fat</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
