// src/app/(auth-pages)/components/form-card.tsx
import { UtensilsCrossed } from "lucide-react";

import {
	Card,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";

interface IFormCardProps {
	title: string;
	description: string;
}

export function FormCard({
	title,
	description,
	children,
}: React.PropsWithChildren<IFormCardProps>) {
	return (
		<Card className="w-full shadow-xl">
			<CardHeader className="space-y-1 flex flex-col items-center">
				<div className="w-12 h-12 bg-foreground rounded-full flex items-center justify-center mb-2">
					<UtensilsCrossed className="h-6 w-6 text-primary" />
				</div>
				<CardTitle className="text-2xl font-bold text-center">
					{title}
				</CardTitle>
				<CardDescription className="text-center">{description}</CardDescription>
			</CardHeader>
			{children}
		</Card>
	);
}

// src/lib/modules/auth/components/form-card.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import { UtensilsCrossed } from '@lucide/svelte';

	let {
		title,
		description,
		children,
		class: className = ''
	}: {
		title: string;
		description: string;
		children: any;
		class?: string;
	} = $props();
</script>

<div class={cn('bg-card text-card-foreground prose w-full rounded-lg border shadow-xl', className)}>
	<div class="flex flex-col items-center p-6 pb-0">
		<div
			class="bg-foreground text-primary mb-2 flex h-12 w-12 items-center justify-center rounded-full"
		>
			<UtensilsCrossed class="h-6 w-6" />
		</div>
		<h3>{title}</h3>
		<p class="text-muted-foreground text-center">{description}</p>
	</div>
	{@render children()}
</div>
