// src/lib/modules/recipes/new/components/instructions-fields.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import * as Form from '$lib/components/ui/form/index';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Plus, Trash2 } from '@lucide/svelte';
	import RecipeFormCard from './recipe-form-card.svelte';
	import type { SuperForm } from 'sveltekit-superforms/client';
	import type { IRecipeFormValues } from '../schema';

	interface Props {
		form: SuperForm<IRecipeFormValues>;
	}

	const { form }: Props = $props();

	const { form: formData } = form;

	function addInstruction() {
		if (!$formData.instructions) {
			$formData.instructions = [];
		}
		$formData.instructions = [...$formData.instructions, ''];
	}

	function removeInstruction(index: number) {
		if ($formData.instructions.length > 1) {
			$formData.instructions = $formData.instructions.filter((_, i) => i !== index);
		}
	}

	function updateInstruction(index: number, value: string) {
		$formData.instructions[index] = value;
	}
</script>

<RecipeFormCard>
	{#snippet children()}
		<div class="mb-4 flex items-center justify-between">
			<h2 class="prose text-xl font-semibold">Instructions</h2>
			<Button type="button" variant="outline" size="sm" onclick={addInstruction}>
				<Plus class="mr-2 h-4 w-4" />
				Add Step
			</Button>
		</div>
		<Form.Field {form} name="instructions">
			<Form.Control>
				{#snippet children({ props })}
					<div class="space-y-4">
						{#each $formData.instructions as instruction, i}
							<div class="flex items-start gap-2">
								<div class="flex-1 space-y-2">
									<Form.Label for="instruction-{i}" class="sr-only">Step {i + 1}</Form.Label>
									<Textarea
										{...props}
										id="instruction-{i}"
										name={props.name}
										placeholder="Describe this step"
										class="min-h-[80px]"
										value={instruction}
										oninput={(e) => updateInstruction(i, e.currentTarget.value)}
									/>
								</div>

								<Button
									type="button"
									variant="ghost"
									size="icon"
									onclick={() => removeInstruction(i)}
									disabled={$formData.instructions.length === 1}
								>
									<Trash2 class="h-4 w-4" />
									<span class="sr-only">Remove step</span>
								</Button>
							</div>
						{/each}
					</div>
				{/snippet}
			</Form.Control>
			<Form.FieldErrors />
		</Form.Field>
	{/snippet}
</RecipeFormCard>

// src/app/(authenticated)/recipes/new/components/instructions-fields.tsx
import { withForm } from "@/components/form";
import { Heading2 } from "@/components/typography";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Plus, Trash2 } from "lucide-react";
import { recipeFormOpts } from "../form-logic/shared-form-code";
import { RecipeFormCard } from "./recipe-form-card";

export const InstructionsFields = withForm({
  ...recipeFormOpts,
  render: ({ form }) => {
    return (
      <RecipeFormCard>
        <form.AppField name="instructions" mode="array">
          {(field) => {
            return (
              <>
                <div className="mb-4 flex items-center justify-between">
                  <Heading2 className="font-semibold text-xl">
                    Instructions
                  </Heading2>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => field.pushValue("")}
                  >
                    <Plus className="mr-2 h-4 w-4" />
                    Add Step
                  </Button>
                </div>
                <div className="space-y-4">
                  {field.state.value.length > 0 &&
                    field.state.value.map((_, i) => {
                      return (
                        // biome-ignore lint/suspicious/noArrayIndexKey: <explanation>
                        <form.AppField key={i} name={`instructions[${i}]`}>
                          {(subField) => {
                            return (
                              <div
                                key={subField.name}
                                className="flex items-start gap-2"
                              >
                                <subField.Item className="flex-1">
                                  <subField.Control>
                                    <Textarea
                                      name={subField.name}
                                      placeholder="Describe this step"
                                      className="min-h-[80px]"
                                      value={subField.state.value}
                                      onBlur={subField.handleBlur}
                                      onChange={(e) =>
                                        subField.handleChange(e.target.value)
                                      }
                                    />
                                  </subField.Control>
                                  <subField.Message />
                                </subField.Item>

                                <Button
                                  type="button"
                                  variant="ghost"
                                  size="icon"
                                  onClick={() => field.removeValue(i)}
                                  disabled={field.state.value.length === 1}
                                >
                                  <Trash2 className="h-4 w-4" />
                                  <span className="sr-only">Remove step</span>
                                </Button>
                              </div>
                            );
                          }}
                        </form.AppField>
                      );
                    })}
                </div>
              </>
            );
          }}
        </form.AppField>
      </RecipeFormCard>
    );
  },
});
