// src/lib/modules/recipes/new/components/recipe-details-fields.svelte
<script lang="ts">
	import { Input } from '$lib/components/ui/input';
	import * as Form from '$lib/components/ui/form/index';
	import * as Select from '$lib/components/ui/select/index';
	import { Textarea } from '$lib/components/ui/textarea';
	import { MEAL_TYPES } from '$lib/constants/meal-types';
	import type { SuperForm } from 'sveltekit-superforms/client';
	import RecipeFormCard from './recipe-form-card.svelte';
	import RecipeImageUpload from './recipe-image-upload.svelte';
	import type { IRecipeFormValues } from '../schema';

	interface Props {
		form: SuperForm<IRecipeFormValues>;
	}

	const { form }: Props = $props();

	const { form: formData } = form;

	function handleImageChange(file?: File) {
		$formData.image = file;
	}
</script>

<RecipeFormCard>
	{#snippet children()}
		<h2 class="prose mb-4 text-xl font-semibold">Recipe Details</h2>
		<div class="grid gap-6 md:grid-cols-2">
			<div class="md:col-span-2">
				<Form.Field {form} name="title">
					<Form.Control>
						{#snippet children({ props })}
							<div class="space-y-2">
								<Form.Label>Recipe Title</Form.Label>
								<Input placeholder="Enter recipe title" {...props} bind:value={$formData.title} />
							</div>
						{/snippet}
					</Form.Control>
					<Form.FieldErrors />
				</Form.Field>
			</div>

			<div class="md:col-span-2">
				<Form.Field {form} name="description">
					<Form.Control>
						{#snippet children({ props })}
							<div class="space-y-2">
								<Form.Label>Description</Form.Label>
								<Textarea
									placeholder="Describe your recipe"
									class="min-h-[100px]"
									{...props}
									bind:value={$formData.description}
								/>
							</div>
						{/snippet}
					</Form.Control>
					<Form.FieldErrors />
				</Form.Field>
			</div>

			<div class="md:col-span-2">
				<Form.Field {form} name="image">
					<Form.Control>
						{#snippet children({ props })}
							<div class="space-y-2">
								<Form.Label>Recipe Image</Form.Label>
								<RecipeImageUpload
									{...props}
									value={$formData.image}
									onchange={handleImageChange}
								/>
							</div>
						{/snippet}
					</Form.Control>
					<Form.FieldErrors />
				</Form.Field>
			</div>
			<Form.Field {form} name="prepTime">
				<Form.Control>
					{#snippet children({ props })}
						<div class="space-y-2">
							<Form.Label>Prep Time (minutes)</Form.Label>
							<Input
								{...props}
								bind:value={$formData.prepTime}
								type="number"
								min="1"
								placeholder="15"
							/>
						</div>
					{/snippet}
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>
			<Form.Field {form} name="cookTime">
				<Form.Control>
					{#snippet children({ props })}
						<div class="space-y-2">
							<Form.Label>Cook Time (minutes)</Form.Label>
							<Input
								{...props}
								bind:value={$formData.cookTime}
								type="number"
								min="1"
								placeholder="15"
							/>
						</div>
					{/snippet}
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>
			<Form.Field {form} name="servings">
				<Form.Control>
					{#snippet children({ props })}
						<div class="space-y-2">
							<Form.Label>Servings</Form.Label>
							<Input
								{...props}
								bind:value={$formData.servings}
								type="number"
								min="1"
								placeholder="15"
							/>
						</div>
					{/snippet}
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>
			<Form.Field {form} name="mealType">
				<Form.Control>
					{#snippet children({ props })}
						<div class="space-y-2">
							<Form.Label>Meal Type</Form.Label>
							<Select.Root type="single" name={props.name} bind:value={$formData.mealType}>
								<Select.Trigger class="w-full" {...props}
									>{$formData.mealType ?? 'Select meal type'}</Select.Trigger
								>
								<Select.Content>
									{#each MEAL_TYPES as mealType}
										<Select.Item value={mealType}>{mealType}</Select.Item>
									{/each}
								</Select.Content>
							</Select.Root>
						</div>
					{/snippet}
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>
		</div>
	{/snippet}
</RecipeFormCard>

// src/app/(authenticated)/recipes/new/components/recipe-details-fields.tsx
import { withForm } from "@/components/form";
import { Heading2 } from "@/components/typography";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { MEAL_TYPES, type MealType } from "@/lib/constants/meal-types";
import { recipeFormOpts } from "../form-logic/shared-form-code";
import { RecipeFormCard } from "./recipe-form-card";
import { RecipeImageUpload } from "./recipe-image-upload";

export const RecipeDetailsFields = withForm({
  ...recipeFormOpts,
  render: ({ form }) => {
    return (
      <RecipeFormCard>
        <Heading2 className="mb-4 font-semibold text-xl">
          Recipe Details
        </Heading2>
        <div className="grid gap-6 md:grid-cols-2">
          <div className="md:col-span-2">
            <form.AppField
              name="title"
              children={(field) => (
                <field.Item>
                  <field.Label>Recipe Title</field.Label>
                  <field.Control>
                    <Input
                      name={field.name}
                      placeholder="Enter recipe title"
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(e) => field.handleChange(e.target.value)}
                    />
                  </field.Control>
                  <field.Message />
                </field.Item>
              )}
            />
          </div>

          <div className="md:col-span-2">
            <form.AppField
              name="description"
              children={(field) => (
                <field.Item>
                  <field.Label>Description</field.Label>
                  <field.Control>
                    <Textarea
                      name={field.name}
                      placeholder="Describe your recipe"
                      className="min-h-[100px]"
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(e) => field.handleChange(e.target.value)}
                    />
                  </field.Control>
                  <field.Message />
                </field.Item>
              )}
            />
          </div>

          <div className="md:col-span-2">
            <form.AppField
              name="image"
              children={(field) => (
                <field.Item>
                  <field.Label>Recipe Image</field.Label>
                  <field.Control>
                    <RecipeImageUpload
                      name={field.name}
                      value={field.state.value as File}
                      onChange={(file) => {
                        field.handleChange(file);
                      }}
                    />
                  </field.Control>
                  <field.Description>
                    Upload an image of your recipe (optional)
                  </field.Description>
                  <field.Message />
                </field.Item>
              )}
            />
          </div>

          <form.AppField
            name="prepTime"
            children={(field) => (
              <field.Item>
                <field.Label>Prep Time (minutes)</field.Label>
                <field.Control>
                  <Input
                    name={field.name}
                    type="number"
                    min={1}
                    placeholder="15"
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                  />
                </field.Control>
                <field.Message />
              </field.Item>
            )}
          />

          <form.AppField
            name="cookTime"
            children={(field) => (
              <field.Item>
                <field.Label>Cook Time (minutes)</field.Label>
                <field.Control>
                  <Input
                    name={field.name}
                    type="number"
                    min={1}
                    placeholder="30"
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                  />
                </field.Control>
                <field.Message />
              </field.Item>
            )}
          />

          <form.AppField
            name="servings"
            children={(field) => (
              <field.Item>
                <field.Label>Servings</field.Label>
                <field.Control>
                  <Input
                    name={field.name}
                    type="number"
                    min={1}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                  />
                </field.Control>
                <field.Message />
              </field.Item>
            )}
          />

          <form.AppField
            name="mealType"
            children={(field) => (
              <field.Item>
                <field.Label>Meal Type</field.Label>
                <field.Control>
                  <Select
                    name={field.name}
                    onValueChange={(value: MealType) =>
                      field.handleChange(value)
                    }
                    defaultValue={field.state.value}
                    value={field.state.value}
                    onOpenChange={field.handleBlur}
                  >
                    <div>
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Select meal type" />
                      </SelectTrigger>
                    </div>
                    <SelectContent>
                      <SelectItem value={MEAL_TYPES[0]}>
                        {MEAL_TYPES[0]}
                      </SelectItem>
                      <SelectItem value={MEAL_TYPES[1]}>
                        {MEAL_TYPES[1]}
                      </SelectItem>
                      <SelectItem value={MEAL_TYPES[2]}>
                        {MEAL_TYPES[2]}
                      </SelectItem>
                      <SelectItem value={MEAL_TYPES[3]}>
                        {MEAL_TYPES[3]}
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </field.Control>
                <field.Message />
              </field.Item>
            )}
          />
        </div>
      </RecipeFormCard>
    );
  },
});
