// src/app/(authenticated)/recipes/components/recipe-list.tsx
import { createClient } from "@/lib/supabase/server";
import { RecipeCard } from "./recipe-card";

export async function RecipeList() {
  const supabase = await createClient();

  const { data, error } = await supabase.from("recipes").select("*");

  if (error) {
    throw new Error(`Error fetching recipes: ${error.message}`);
  }

  if (!data || data.length === 0) {
    return (
      <div className="py-10 text-center">
        No recipes found. Add some recipes to get started!
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
      {data.map((recipe) => (
        <RecipeCard key={recipe.id} recipe={recipe} />
      ))}
    </div>
  );
}

// src/lib/modules/recipes/components/recipe-list.svelte
<script lang="ts">
	import RecipeCard from './recipe-card.svelte';
	import type { Recipe } from '../types';

	let { recipes }: { recipes: Recipe[] } = $props();
</script>

{#if recipes.length === 0}
	<div class="py-10 text-center">No recipes found. Add some recipes to get started!</div>
{:else}
	<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
		{#each recipes as recipe (recipe.id)}
			<RecipeCard {recipe} />
		{/each}
	</div>
{/if}
